"""Per-dashboard artifact packages.

package_dashboard() writes one self-contained directory per converted
dashboard with everything a Grafana operator needs for a copy-paste
import that just works: the dashboard JSON, the machine-readable
requirements/widget reports, a human README (datasources to create,
plugins to install, import steps, troubleshooting), plus a data smoke
test (datatest.json manifest + executable test.sh runner).

write_index() summarizes all packages of one run into <out>/INDEX.md.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Tuple

from .livecheck import iter_targets

SCHEMA_DATATEST = "nr2grafana/datatest/v1"

CONFIDENCES = ("exact", "approximate", "needs-review", "untranslatable")

# Keys a query expression may live under, per datasource family (see
# grafana/builder._make_targets): prometheus/loki use "expr", tempo uses
# "query" (TraceQL), the New Relic passthrough plugin uses "queryText".
_EXPR_KEYS = ("expr", "query", "queryText")


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------

def _family(ds_type: str) -> str:
    """Map a target's datasource plugin type to a datasource family."""
    t = (ds_type or "").lower()
    if "newrelic" in t:
        return "newrelic"
    if t in ("prometheus", "loki", "tempo"):
        return t
    return t or "prometheus"


def _md_cell(text: Any) -> str:
    """Make a value safe inside a markdown table cell."""
    s = str(text if text is not None else "")
    return s.replace("|", "\\|").replace("\n", " ").strip()


def _write_json(path: str, data: Any) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, ensure_ascii=True)
        f.write("\n")


def _write_text(path: str, text: str) -> None:
    if not text.endswith("\n"):
        text += "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def _confidence_counts(report: List[Dict[str, Any]]) -> Dict[str, int]:
    counts = {c: 0 for c in CONFIDENCES}
    for entry in report or []:
        c = entry.get("confidence", "")
        if c in counts:
            counts[c] += 1
    return counts


def _widget_label(entry: Dict[str, Any]) -> str:
    """Widget title from a report entry (both key spellings)."""
    return (entry.get("widget_title") or entry.get("widget")
            or "(untitled)")


# ---------------------------------------------------------------------------
# datatest.json
# ---------------------------------------------------------------------------

def build_datatest(dash: Dict[str, Any],
                   widget_report: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Machine manifest of per-panel test queries (raw exprs, no
    variable substitution) for grafana/live.py and test.sh."""
    conf_by_id: Dict[Any, str] = {}
    for entry in widget_report or []:
        conf_by_id[entry.get("panel_id")] = entry.get("confidence", "")

    targets: List[Dict[str, Any]] = []
    for panel, tgt in iter_targets(dash):
        expr = ""
        for key in _EXPR_KEYS:
            val = tgt.get(key)
            if isinstance(val, str) and val.strip():
                expr = val
                break
        if not expr:
            continue
        ds = tgt.get("datasource") or {}
        confidence = conf_by_id.get(panel.get("id"), "")
        targets.append({
            "panel_id": panel.get("id"),
            "panel_title": panel.get("title") or "",
            "refId": tgt.get("refId") or "A",
            "datasource_family": _family(ds.get("type", "")),
            "ds_uid_ref": ds.get("uid", ""),
            "expr": expr,
            "expect": ("data" if confidence in ("exact", "approximate")
                       else "any"),
        })
    return {
        "schema": SCHEMA_DATATEST,
        "dashboard": dash.get("title", ""),
        "uid": dash.get("uid", ""),
        "targets": targets,
    }


# ---------------------------------------------------------------------------
# test.sh
# ---------------------------------------------------------------------------

# POSIX sh + curl + an embedded python3 helper (stdlib only, no jq).
# @TITLE@ is replaced at package time.
_TEST_SH = r'''#!/bin/sh
# Data smoke test for "@TITLE@" -- generated by nr2grafana.
#
# Runs every query in datatest.json against a live Grafana instance via
# POST /api/ds/query, resolving the datasource by type from
# GET /api/datasources (first datasource of the matching type wins).
#
# Usage:
#   GRAFANA_URL=https://grafana.example.com GRAFANA_TOKEN=glsa_... sh test.sh
#
# Output, one line per query:
#   PASS     query ran and returned data
#   NO-DATA  query ran but returned nothing (warning: metric/labels may
#            not exist in your stack yet -- see README troubleshooting)
#   FAIL     Grafana rejected the query or the request errored
# Exit code: 1 if any query FAILed, else 0. NO-DATA never fails the run.
#
# Needs: curl, python3 (used to read datatest.json -- no jq required).

set -u

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MANIFEST="$DIR/datatest.json"

if [ -z "${GRAFANA_URL:-}" ] || [ -z "${GRAFANA_TOKEN:-}" ]; then
    echo "error: set GRAFANA_URL and GRAFANA_TOKEN first, e.g." >&2
    echo "  GRAFANA_URL=https://grafana.example.com \\" >&2
    echo "  GRAFANA_TOKEN=glsa_xxx sh $0" >&2
    echo "(GRAFANA_TOKEN is a Grafana service account token)" >&2
    exit 2
fi
GRAFANA_URL=${GRAFANA_URL%/}

command -v curl >/dev/null 2>&1 || { echo "error: curl not found" >&2
    exit 2; }
command -v python3 >/dev/null 2>&1 || {
    echo "error: python3 not found (needed to read datatest.json)" >&2
    exit 2; }
[ -f "$MANIFEST" ] || { echo "error: $MANIFEST not found" >&2; exit 2; }

HELPER=$(cat <<'PYEOF'
import json, re, sys

TYPE_OF = {"prometheus": "prometheus", "loki": "loki", "tempo": "tempo"}


def load(path):
    with open(path) as f:
        return json.load(f)


def targets(path):
    return load(path).get("targets") or []


def subst(expr):
    """Grafana template vars -> concrete values so queries parse.

    Equality matchers on variables become match-alls so panels that
    filter on a variable can still find data.
    """
    subs = [
        (r'=\s*"\$\{[A-Za-z_][A-Za-z0-9_:]*\}"', '=~".+"'),
        (r'=\s*"\$[A-Za-z_][A-Za-z0-9_]*"', '=~".+"'),
        (r'"\$\{[A-Za-z_][A-Za-z0-9_:]*\}"', '".+"'),
        (r'"\$[A-Za-z_][A-Za-z0-9_]*"', '".+"'),
        (r"\$__rate_interval", "5m"),
        (r"\$__interval", "1m"),
        (r"\$__range", "1h"),
        (r"\$__auto", "5m"),
        (r"\$\{[A-Za-z_][A-Za-z0-9_:]*\}", "x"),
        (r"\$[A-Za-z_][A-Za-z0-9_]*", "x"),
    ]
    for pat, rep in subs:
        expr = re.sub(pat, rep, expr)
    return expr


def resolve(dsfile, fam):
    """First datasource of the matching type -> (uid, type)."""
    try:
        dss = load(dsfile)
    except Exception:
        return None, None
    if not isinstance(dss, list):
        return None, None
    for ds in dss:
        t = (ds.get("type") or "").lower()
        if fam == "newrelic":
            if "newrelic" in t:
                return ds.get("uid"), ds.get("type")
        elif t == TYPE_OF.get(fam, fam):
            return ds.get("uid"), ds.get("type")
    return None, None


def cmd_count(manifest):
    print(len(targets(manifest)))


def cmd_line(manifest, i):
    t = targets(manifest)[int(i)]
    title = (t.get("panel_title") or "").replace("|", "/")
    print("|".join([str(t.get("panel_id")), t.get("refId") or "A",
                    t.get("datasource_family") or "", title]))


def cmd_body(manifest, dsfile, i):
    t = targets(manifest)[int(i)]
    fam = t.get("datasource_family") or "prometheus"
    uid, dstype = resolve(dsfile, fam)
    if not uid:
        sys.stderr.write(
            "no %s datasource on this Grafana instance; add one under "
            "Connections -> Data sources\n" % fam)
        sys.exit(3)
    expr = subst(t.get("expr") or "")
    q = {"refId": t.get("refId") or "A",
         "datasource": {"type": dstype, "uid": uid}}
    if fam == "tempo":
        q.update({"queryType": "traceql", "query": expr, "limit": 20})
    elif fam == "loki":
        q.update({"expr": expr, "queryType": "range", "maxLines": 20})
    elif fam == "newrelic":
        q.update({"queryText": t.get("expr") or "",
                  "useGrafanaTime": True})
    else:
        q.update({"expr": expr, "format": "time_series", "range": True,
                  "instant": False, "intervalMs": 60000,
                  "maxDataPoints": 200})
    print(json.dumps({"queries": [q], "from": "now-1h", "to": "now"}))


def cmd_check(respfile, refid, http_code):
    try:
        body = load(respfile)
    except Exception:
        print("FAIL no JSON response from Grafana (HTTP %s)" % http_code)
        return
    if not isinstance(body, dict) or "results" not in body:
        msg = ""
        if isinstance(body, dict):
            msg = body.get("message") or ""
        print("FAIL %s" % (msg or "HTTP %s" % http_code)[:200])
        return
    res = body["results"].get(refid)
    if res is None:
        vals = list(body["results"].values())
        res = vals[0] if vals else {}
    err = res.get("error") or ""
    if err:
        print("FAIL %s" % str(err)[:200])
        return
    frames = res.get("frames") or []
    points = 0
    for fr in frames:
        for col in ((fr.get("data") or {}).get("values") or []):
            points += len(col or [])
    if points:
        print("PASS")
    else:
        print("NO-DATA")


CMDS = {"count": cmd_count, "line": cmd_line, "body": cmd_body,
        "check": cmd_check}
CMDS[sys.argv[1]](*sys.argv[2:])
PYEOF
)

WORK=$(mktemp -d) || exit 2
trap 'rm -rf "$WORK"' EXIT INT TERM

DSFILE="$WORK/datasources.json"
code=$(curl -sS -m 30 -o "$DSFILE" -w '%{http_code}' \
    -H "Authorization: Bearer $GRAFANA_TOKEN" \
    "$GRAFANA_URL/api/datasources") || {
    echo "error: cannot reach $GRAFANA_URL -- check the URL and network" >&2
    exit 1
}
case "$code" in
    200) ;;
    401|403)
        echo "error: Grafana rejected the token (HTTP $code)." >&2
        echo "Use a service account token with at least Viewer role." >&2
        exit 1 ;;
    *)
        echo "error: GET /api/datasources returned HTTP $code" >&2
        exit 1 ;;
esac

n=$(python3 -c "$HELPER" count "$MANIFEST") || {
    echo "error: could not read $MANIFEST" >&2; exit 2; }
if [ "$n" -eq 0 ]; then
    echo "nothing to test: datatest.json lists no queries"
    exit 0
fi

echo "Testing $n queries against $GRAFANA_URL ..."
pass=0; nodata=0; fail=0
i=0
while [ "$i" -lt "$n" ]; do
    line=$(python3 -c "$HELPER" line "$MANIFEST" "$i")
    pid=${line%%|*};  rest=${line#*|}
    refid=${rest%%|*}; rest=${rest#*|}
    fam=${rest%%|*};  title=${rest#*|}
    label="panel $pid [$refid] ($fam) $title"

    if body=$(python3 -c "$HELPER" body "$MANIFEST" "$DSFILE" "$i" \
            2>"$WORK/err"); then
        code=$(printf '%s' "$body" | curl -sS -m 60 -o "$WORK/resp.json" \
            -w '%{http_code}' \
            -H "Authorization: Bearer $GRAFANA_TOKEN" \
            -H "Content-Type: application/json" \
            -X POST "$GRAFANA_URL/api/ds/query" -d @-) || code=000
        verdict=$(python3 -c "$HELPER" check "$WORK/resp.json" \
            "$refid" "$code")
    else
        verdict="FAIL $(cat "$WORK/err")"
    fi

    case "$verdict" in
        PASS*)    pass=$((pass + 1));     echo "PASS     $label" ;;
        NO-DATA*) nodata=$((nodata + 1)); echo "NO-DATA  $label" ;;
        *)        fail=$((fail + 1));     echo "FAIL     $label"
                  echo "         ${verdict#FAIL }" ;;
    esac
    i=$((i + 1))
done

echo
echo "result: $pass passed, $nodata no-data, $fail failed (of $n)"
if [ "$fail" -gt 0 ]; then
    exit 1
fi
exit 0
'''


def render_test_sh(title: str) -> str:
    safe = (title or "dashboard").replace("\n", " ").replace('"', "'")
    return _TEST_SH.replace("@TITLE@", safe)


# ---------------------------------------------------------------------------
# README.md
# ---------------------------------------------------------------------------

def _readme_datasources(req: Dict[str, Any]) -> List[str]:
    lines: List[str] = ["### Required datasources", ""]
    dss = req.get("datasources") or []
    if not dss:
        lines.append("_None -- the dashboard has no live queries._")
        lines.append("")
        return lines
    lines += [
        "| Name | Plugin id | Core | Purpose | Referenced as |",
        "|---|---|---|---|---|",
    ]
    for ds in dss:
        fam = ds.get("family", "")
        lines.append("| %s | `%s` | %s | %s | `%s` |" % (
            _md_cell(fam.capitalize() or "?"),
            _md_cell(ds.get("plugin_id") or fam),
            "yes" if ds.get("core") else "no",
            _md_cell(ds.get("purpose") or ""),
            _md_cell(ds.get("uid_ref") or "")))
    lines += [
        "",
        "To add one in the Grafana UI: **Connections -> Data sources ->",
        "Add new data source**, pick the plugin above, set the URL of your",
        "backend (Mimir/Prometheus, Loki, Tempo, ...), then **Save & test**.",
        "The dashboard references datasources through template variables,",
        "so your datasource names do not need to match anything -- you pick",
        "them at import time.",
        "",
    ]
    return lines


def _readme_plugins(req: Dict[str, Any]) -> List[str]:
    plugins = req.get("plugins") or []
    if not plugins:
        return []
    lines = ["### Plugins to install", ""]
    for p in plugins:
        pid = p.get("id", "")
        reason = p.get("reason") or ""
        cmd = p.get("grafana_cli") or (
            "grafana-cli plugins install %s" % pid)
        lines.append("- `%s`%s" % (pid, (" -- " + reason) if reason else ""))
        lines += ["", "  ```sh", "  %s" % cmd, "  ```", ""]
    lines.append("Restart Grafana after installing plugins.")
    lines.append("")
    return lines


def _readme_domains(req: Dict[str, Any]) -> List[str]:
    domains = req.get("domains") or []
    if not domains:
        return []
    lines = [
        "### Data domains detected",
        "",
        "The source dashboard uses New Relic data that maps to these",
        "domains. Each needs a matching data pipeline or datasource on",
        "your side before the panels show data:",
        "",
    ]
    for d in domains:
        pids = ", ".join(str(p) for p in d.get("panel_ids") or [])
        lines.append("- **%s**%s" % (
            d.get("domain", "?"),
            (" (panels %s)" % pids) if pids else ""))
        for ev in (d.get("evidence") or [])[:3]:
            lines.append("  - evidence: `%s`" % _md_cell(ev))
        for opt in d.get("options") or []:
            kind = opt.get("kind", "option")
            note = opt.get("note") or ""
            plug = opt.get("plugin_id")
            extra = (" (`%s`)" % plug) if plug else ""
            lines.append("  - %s%s: %s" % (kind, extra, note))
    lines.append("")
    return lines


def _readme_nr_native(req: Dict[str, Any],
                      report: List[Dict[str, Any]]) -> List[str]:
    native = req.get("nr_native") or []
    if not native:
        return []
    titles = {e.get("panel_id"): _widget_label(e) for e in report or []}
    lines = [
        "## New Relic-native widgets",
        "",
        "These widgets have no direct LGTM equivalent as-is; each is",
        "listed with its closest option(s):",
        "",
    ]
    for w in native:
        pid = w.get("panel_id")
        title = titles.get(pid, "")
        head = "- Panel %s%s (`%s`)" % (
            pid, (" %r" % title) if title else "", w.get("widget", "?"))
        lines.append(head)
        if w.get("why"):
            lines.append("  - why: %s" % w["why"])
        if w.get("equivalent"):
            lines.append("  - equivalent: %s" % w["equivalent"])
    lines.append("")
    return lines


def _readme_import(req: Dict[str, Any]) -> List[str]:
    lines = ["## Import", "", "### Grafana UI", ""]
    steps = (req.get("import") or {}).get("steps") or []
    if steps:
        for i, step in enumerate(steps):
            s = str(step).strip()
            # steps may already be numbered ("1. ...")
            if s[:1].isdigit() and "." in s[:4]:
                lines.append(s)
            else:
                lines.append("%d. %s" % (i + 1, s))
    else:
        lines += [
            "1. Create the required datasources above.",
            "2. **Dashboards -> New -> Import**.",
            "3. Paste the contents of `dashboard.json` (or upload the "
            "file) and click **Load**.",
            "4. When prompted, pick a datasource for each variable, then "
            "**Import**.",
        ]
    lines += [
        "",
        "### Grafana API",
        "",
        "From this directory, with a service account token:",
        "",
        "```sh",
        "export GRAFANA_URL=https://grafana.example.com",
        "export GRAFANA_TOKEN=glsa_...   # service account token",
        "curl -sS -X POST \"$GRAFANA_URL/api/dashboards/db\" \\",
        "  -H \"Authorization: Bearer $GRAFANA_TOKEN\" \\",
        "  -H \"Content-Type: application/json\" \\",
        "  -d \"{\\\"dashboard\\\": $(cat dashboard.json), "
        "\\\"overwrite\\\": false, \\\"folderUid\\\": \\\"\\\"}\"",
        "```",
        "",
        "Keep `overwrite: false` for the first import (a title collision",
        "then fails loudly instead of replacing another dashboard); switch",
        "to `true` only when re-importing this same dashboard.",
        "",
    ]
    return lines


def _readme_troubleshooting(req: Dict[str, Any]) -> List[str]:
    lines = [
        "## Troubleshooting",
        "",
        "**Import prompts for datasources** -- expected. The dashboard",
        "references datasources through template variables; pick your",
        "Prometheus/Mimir, Loki and Tempo instances when asked. If a",
        "dropdown is empty, the matching datasource does not exist yet",
        "(see the table above).",
        "",
        "**Panels show \"No data\"** -- the query is valid but nothing in",
        "your stack matches it yet. Each panel expects specific",
        "metrics/labels or log streams:",
        "",
    ]
    expectations = req.get("data_expectations") or []
    for exp in expectations:
        needs = exp.get("needs") or {}
        parts = []
        metrics = needs.get("metrics") or []
        labels = needs.get("labels") or []
        selector = needs.get("stream_selector") or ""
        if metrics:
            parts.append("metrics " + ", ".join(
                "`%s`" % m for m in metrics))
        if selector:
            parts.append("log stream `%s`" % _md_cell(selector))
        if labels:
            parts.append("labels " + ", ".join(
                "`%s`" % l for l in labels))
        lines.append("- panel %s (%s): needs %s" % (
            exp.get("panel_id"), exp.get("datasource", "?"),
            "; ".join(parts) or "(see widget-report.json)"))
    if not expectations:
        lines.append("- see `requirements.json` (`data_expectations`) "
                     "and `widget-report.json`")
    lines += [
        "",
        "Common no-data causes: the OTel collector/exporter does not emit",
        "those metrics yet, your stack uses different label names (fix via",
        "`label_map`/`metric_map` in the converter config and reconvert),",
        "or the selected time range is empty.",
        "",
        "**Verify with the bundled smoke test** -- runs every panel query",
        "against your Grafana and prints PASS / NO-DATA / FAIL per query:",
        "",
        "```sh",
        "GRAFANA_URL=https://grafana.example.com GRAFANA_TOKEN=glsa_... \\",
        "  sh test.sh",
        "```",
        "",
        "FAIL lines mean Grafana rejected the query (bad datasource,",
        "missing plugin, or a query needing manual review); NO-DATA lines",
        "are warnings only. `datatest.json` is the machine-readable",
        "manifest behind `test.sh`.",
    ]
    return lines


def render_readme(slug: str, dash: Dict[str, Any],
                  widget_report: List[Dict[str, Any]],
                  requirements: Dict[str, Any],
                  cfg: Optional[Dict[str, Any]] = None) -> str:
    req = requirements or {}
    report = widget_report or []
    title = dash.get("title") or req.get("dashboard") or slug
    counts = _confidence_counts(report)

    lines: List[str] = [
        "# %s" % title,
        "",
        "Converted from the New Relic dashboard \"%s\" by %s." % (
            req.get("dashboard") or title,
            req.get("generated_by") or "nr2grafana"),
        "",
        "- Grafana UID: `%s`" % dash.get("uid", ""),
        "- Package: `%s/`" % slug,
        "- Panels with queries: %d" % len(report),
        "",
        "## Panel confidence",
        "",
        "| Confidence | Panels | Meaning |",
        "|---|--:|---|",
        "| exact | %d | semantically equivalent |" % counts["exact"],
        "| approximate | %d | close; minor semantic drift |"
        % counts["approximate"],
        "| needs-review | %d | translated but verify by hand "
        "(`[REVIEW]` in title) |" % counts["needs-review"],
        "| untranslatable | %d | placeholder or NR passthrough "
        "(`[MANUAL]` in title) |" % counts["untranslatable"],
        "",
    ]
    flagged = [e for e in report
               if e.get("confidence") in ("needs-review", "untranslatable")]
    if flagged:
        lines.append("Panels to review:")
        lines.append("")
        for e in flagged:
            lines.append("- panel %s %r (%s)" % (
                e.get("panel_id"), _widget_label(e),
                e.get("confidence")))
        lines.append("")

    lines += ["## Before you import", ""]
    lines += _readme_datasources(req)
    lines += _readme_plugins(req)
    lines += _readme_domains(req)
    lines += _readme_nr_native(req, report)
    lines += _readme_import(req)
    lines += _readme_troubleshooting(req)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# public API
# ---------------------------------------------------------------------------

def package_dashboard(out_dir: str, slug: str, dash: Dict[str, Any],
                      widget_report: List[Dict[str, Any]],
                      requirements: Dict[str, Any],
                      cfg: Dict[str, Any]) -> str:
    """Write <out_dir>/<slug>/ with dashboard.json, requirements.json,
    widget-report.json, README.md, datatest.json and an executable
    test.sh. Returns the package directory path."""
    pkg = os.path.join(out_dir, slug)
    os.makedirs(pkg, exist_ok=True)

    _write_json(os.path.join(pkg, "dashboard.json"), dash)
    _write_json(os.path.join(pkg, "requirements.json"), requirements or {})
    _write_json(os.path.join(pkg, "widget-report.json"), widget_report or [])
    _write_json(os.path.join(pkg, "datatest.json"),
                build_datatest(dash, widget_report or []))
    _write_text(os.path.join(pkg, "README.md"),
                render_readme(slug, dash, widget_report or [],
                              requirements or {}, cfg))
    test_sh = os.path.join(pkg, "test.sh")
    _write_text(test_sh, render_test_sh(dash.get("title") or slug))
    os.chmod(test_sh, 0o755)
    return pkg


def _index_row(entry: Dict[str, Any]) -> Tuple[str, ...]:
    req = entry.get("requirements") or {}
    report = entry.get("widget_report") or entry.get("report") or []
    title = (entry.get("title") or req.get("dashboard")
             or entry.get("slug") or "?")
    pkg_dir = (entry.get("dir") or entry.get("package_dir")
               or entry.get("slug") or "")
    dirname = os.path.basename(str(pkg_dir).rstrip("/"))
    counts = (entry.get("counts") or entry.get("confidence")
              or _confidence_counts(report))
    panels = entry.get("panels")
    if not isinstance(panels, int):
        panels = len(report) or sum(counts.values())
    datasources = entry.get("datasources")
    if not datasources:
        datasources = [d.get("family", "") for d in
                       req.get("datasources") or []]
    datasources = [str(d) for d in datasources if d]
    domains = entry.get("domains")
    if not domains:
        domains = [d.get("domain", "") for d in req.get("domains") or []]
    domains = [str(d) for d in domains if d]
    link = "[`%s/`](%s/README.md)" % (dirname, dirname) if dirname else ""
    return (
        _md_cell(title), link, str(panels),
        str(counts.get("exact", 0)), str(counts.get("approximate", 0)),
        str(counts.get("needs-review", 0)),
        str(counts.get("untranslatable", 0)),
        _md_cell(", ".join(datasources) or "-"),
        _md_cell(", ".join(domains) or "-"),
    )


def write_index(out_dir: str, entries: List[Dict[str, Any]]) -> str:
    """Write <out_dir>/INDEX.md summarizing all packaged dashboards.
    Returns the index file path."""
    lines = [
        "# Migration index",
        "",
        "Generated by nr2grafana. Each directory below is a",
        "self-contained package for one dashboard:",
        "",
        "- `dashboard.json` -- import this into Grafana",
        "- `README.md` / `requirements.json` -- what must exist first",
        "  (datasources, plugins, data pipelines) and how to import",
        "- `widget-report.json` -- per-panel translation confidence",
        "- `test.sh` + `datatest.json` -- live per-query data smoke test",
        "",
        "Suggested workflow per dashboard:",
        "",
        "1. Read `<dir>/README.md`; create the required datasources.",
        "2. Import `dashboard.json` (UI paste, or the curl in the README).",
        "3. `GRAFANA_URL=... GRAFANA_TOKEN=... sh <dir>/test.sh`",
        "4. Fix panels flagged needs-review/untranslatable, fold the fixes",
        "   into the converter config, reconvert.",
        "",
        "| Dashboard | Package | Panels | Exact | Approx | Review "
        "| Manual | Datasources | Domains |",
        "|---|---|--:|--:|--:|--:|--:|---|---|",
    ]
    for entry in entries or []:
        lines.append("| " + " | ".join(_index_row(entry)) + " |")
    if not entries:
        lines.append("| _no dashboards packaged_ | | | | | | | | |")
    path = os.path.join(out_dir, "INDEX.md")
    os.makedirs(out_dir, exist_ok=True)
    _write_text(path, "\n".join(lines))
    return path
